# Generated by Django 3.2 on 2021-05-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0002_snippet_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='input',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='output',
            field=models.TextField(default=''),
        ),
    ]
