# Generated by Django 3.2 on 2021-05-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0003_auto_20210513_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(default='Enter Code Here'),
        ),
    ]
