# Generated by Django 3.2 on 2021-05-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycompiler', '0005_alter_snippet_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='input',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='output',
            field=models.TextField(blank=True),
        ),
    ]
